---
# Reference: https://borgbackup.readthedocs.io/en/stable/deployment/central-backup-server.html
- hosts: backup01.srv.local
  vars:
    user: backup
    group: backup
    home: /home/backup
    pool: "{{ home }}/repos"
    auth_users:
      - host: johndoe.clnt.local
        key: "{{ lookup('file', '/path/to/keys/johndoe.clnt.local.pub') }}"
      - host: web01.clnt.local
        key: "{{ lookup('file', '/path/to/keys/web01.clnt.local.pub') }}"
      - host: app01.clnt.local
        key: "{{ lookup('file', '/path/to/keys/app01.clnt.local.pub') }}"
  tasks:
    - name: Install borg
      ansible.builtin.package:
        name: borg
        state: present
    - name: Create user group
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
    - name: Create user
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ group }}"
        home: "{{ home }}"
        shell: /bin/bash
        createhome: true
        groups: []
        state: present
    - name: "Make backup home only readable by user"
      ansible.builtin.file:
        path: "{{ home }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
        state: directory
    - name: "Create ssh directory"
      ansible.builtin.file:
        path: "{{ home }}/.ssh"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
        state: directory
    - name: "Create backup pool directory"
      ansible.builtin.file:
        path: "{{ pool }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
        state: directory
    - name: "Add client ssh keys"
      ansible.posix.authorized_key:
        user: "{{ user }}"
        key: "{{ item.key }}"
        key_options: 'command="cd {{ pool }}/{{ item.host }};borg serve --restrict-to-path {{ pool }}/{{ item.host }}",restrict'
      with_items: "{{ auth_users }}"
    - name: "Make ssh authorized keys read only"
      ansible.builtin.file:
        path: "{{ home }}/.ssh/authorized_keys"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0600
        state: file
    - name: "Create client backup directories"
      ansible.builtin.file:
        path: "{{ pool }}/{{ item.host }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
        state: directory
      with_items: "{{ auth_users }}"
