---
- import_playbook: nebula.yml
- name: GlusterFS Client
  hosts: gluster_client
  become: yes
  become_user: root
  vars:
    gluster_volume: "ivol"
    gluster_host: "{{ hostvars[groups['gluster'][0]]['nebula_ip'] }}"

  tasks:
    - name: "Mount gluster volume"
      ansible.posix.mount:
        path: /mnt/{{gluster_volume}}
        src: "{{gluster_host}}:/{{gluster_volume}}"
        fstype: gluster
        state: present
