
---
- name: Jackett
  hosts: jackett
  become: yes
  become_user: root
  roles:
    - role: jackett
  
  tasks:
    - name: Allow connections on Jackett port
      ansible.builtin.iptables:
        action: insert
        rule_num: 1
        ctstate: NEW
        chain: INPUT
        protocol: tcp
        destination: "{{ nebula_ip }}"
        destination_port: "{{ jackett_config.port | default(9117) }}"
        jump: ACCEPT
