---
- name: Setup Nebula
  hosts: nebula
  roles:
    - role: install_nebula
      nebula_am_lighthouse: "{{ 'lighthouses' in group_names}}"
      nebula_port: 4242
      nebula_key: "{{lookup('file', 'certs/' + inventory_hostname + '.key')}}"
      nebula_cert: "{{lookup('file', 'certs/' + inventory_hostname + '.crt')}}"
      nebula_ca_cert: "{{lookup('file', 'certs/ca.crt')}}"
      become: yes
      become_user: root

  tasks:
    - name: Allow connections on nebula port
      ansible.builtin.iptables:
        action: insert
        rule_num: 2
        ctstate: NEW
        chain: INPUT
        protocol: udp
        destination_port: 4242
        jump: ACCEPT
      become: yes
      become_user: root
      when: "'lighthouses' in group_names"