---
# Reference: https://borgbackup.readthedocs.io/en/stable/deployment/central-backup-server.html
- name: "NGINX Proxy Manager"
  hosts: proxy
  become: true
  vars:
    nginx_proxy_manager_version: "2.10.1"
    nginx_proxy_manager_admin_port: "81"
    nginx_proxy_manager_user: "proxy"
    nginx_proxy_manager_group: "proxy"
    nginx_proxy_manager_home: "/usr/share/nginx-proxy-manager"
    nginx_proxy_manager_data_dir: "{{ nginx_proxy_manager_home }}/data"
    nginx_proxy_manager_letsencrypt_dir: "{{ nginx_proxy_manager_home }}/letsencrypt"
  roles:
    - role: install_docker
      tags:
        - dependency
  tasks:
    - name: "Create NGINX Proxy Manager group"
      ansible.builtin.group:
        name: "{{ nginx_proxy_manager_group }}"
        state: present
      register: nginx_proxy_manager_group_info
      tags:
        - start-service # register variable used in luanch

    - name: "Create NGINX Proxy Manager user"
      ansible.builtin.user:
        name: "{{ nginx_proxy_manager_user }}"
        comment: "NGINX Proxy Manager User"
        group: "{{ nginx_proxy_manager_group }}"
        state: present
        password_lock: true
        home: "{{ nginx_proxy_manager_home }}"
      register: nginx_proxy_manager_user_info
      tags:
        - start-service # register variable used in luanch

    - name: Create data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ nginx_proxy_manager_user }}"
        group: "{{ nginx_proxy_manager_group }}"
      become_user: "{{ nginx_proxy_manager_user }}"
      with_items:
        - "{{ nginx_proxy_manager_data_dir }}"
        - "{{ nginx_proxy_manager_letsencrypt_dir }}"

    - name: Start and enable docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add python docker package (needed for community package)
      ansible.builtin.pip:
        name: docker
      tags:
        - dependency

    - name: Open standard HTTP ports
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      tags: firewall
      with_items:
        - "80"
        - "443"

    - name: Open admin interface port
      ansible.posix.firewalld:
        port: "{{ nginx_proxy_manager_admin_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      tags: firewall

    - name: Create NGINX Proxy Manager docker container
      community.docker.docker_container:
        name: nginx-proxy-manager
        image: "jc21/nginx-proxy-manager:{{ nginx_proxy_manager_version }}"
        pull: true
        network_mode: bridge
        restart_policy: unless-stopped
        state: started
        env:
          PUID: "{{ nginx_proxy_manager_user_info.uid }}"
          PGID: "{{ nginx_proxy_manager_group_info.gid }}"
        ports:
          - "80:80"
          - "443:443"
          - "{{ nginx_proxy_manager_admin_port }}:81"
        volumes:
          - "{{ nginx_proxy_manager_data_dir }}:/data:Z"
          - "{{ nginx_proxy_manager_letsencrypt_dir }}:/etc/letsencrypt:Z"
      tags:
        - start-service
