
---
# - import_playbook: gluster-client.yml
- name: Plex
  hosts: plex
  become: yes
  become_user: root
  vars:
    uid: 1000
    gid: 1000
    media: "/mnt/ivol"

  tasks:
    - name: chown gluster mount
      ansible.builtin.file:
        path: "{{media}}"
        owner: "{{uid | string}}"
        group: "{{gid | string}}"

    - name: Add python docker package
      ansible.builtin.pip:
        name: docker

    - name: Create plex docker container
      community.docker.docker_container:
        name: plex
        image: linuxserver/plex
        pull: true
        network_mode: bridge
        volumes:
          - "/opt/plex:/config"
          - "{{media}}:/media"

        env:
          PUID: "{{uid | string}}"
          PGID: "{{gid | string}}"

        ports:
          - 32400:32400
          - 1900:1900/udp
          - 3005:3005
          - 5353:5353/udp
          - 8324:8324
          - 32410:32410/udp
          - 32412:32412/udp
          - 32413:32413/udp
          - 32414:32414/udp
          - 32469:32469
