
---
# - import_playbook: gluster-client.yml
- name: Radarr
  hosts: radarr
  become: yes
  become_user: root
  vars:
    media: "/mnt/ivol"
  roles:
    - role: radarr
      radarr_state: started
      radarr_config:
        url_base: /ctrl/radarr