
---
- import_playbook: gluster-client.yml
- name: Transmission
  hosts: transmission
  become: yes
  become_user: root
  vars:
    transmission_home: "/var/lib/transmission-daemon"
    download_dir: "/mnt/ivol/downloads"
    transmission_user: debian-transmission
    transmission_group: debian-transmission

  tasks:
      - name: chown gluster mount
      ansible.builtin.file:
        path: "{{media}}"
        owner: "transmission_user"
        group: "transmission_user"

    - name: Install transmission
      ansible.builtin.package:
        name: transmission-daemon
        state: present

    # Transmission overwrites config on exit
    - name: Stop transmission before writing config
      ansible.builtin.service:
        name: transmission-daemon
        state: stopped

    - name: template transmission config
      ansible.builtin.template:
        src: templates/transmission.json.j2
        dest: "{{transmission_home}}/.config/transmission-daemon/settings.json"
        owner: "{{transmission_user}}"
        group: "{{transmission_user}}"
        force: true
        mode: '0600'

    - name: Start transmission
      ansible.builtin.service:
        name: transmission-daemon
        state: started

    - name: Allow connections on transmission TCP port
      ansible.builtin.iptables:
        action: insert
        rule_num: 1
        ctstate: NEW
        chain: INPUT
        protocol: tcp
        destination: "{{nebula_ip}}"
        destination_port: 9091
        jump: ACCEPT
