---
- name: Wireguard Server
  hosts: all
  tags:
    - wireguard-server
    - wireguard
  vars:
    wgeasy_data_dir: "/opt/wgeasy"
    wgeasy_host: "{{ansible_host}}"
    wgeasy_password: "password"
    wgeasy_default_address: "10.8.0.x"

    pihole_data_dir: "/opt/pihole"
    pihole_password: "password"

    wg_docker_network_subnet: "10.8.1.0/24"
    wg_docker_network_addresses:
      wgeasy: "10.8.1.2"
      pihole: "10.8.1.3"
      nginx: "10.8.1.4"

  become: true
  roles:
    - role: wireguard
      tags:
        - install
    - role: install_docker
      tags:
        - install

  tasks:
    - name: Start and enable docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      tags:
        - pihole
        - wgeasy

    - name: Create wgeasy docker network
      community.docker.docker_network:
        name: wgeasy
        ipam_config:
          - subnet: "{{ wg_docker_network_subnet }}"
      tags:
        - pihole
        - wgeasy

    - name: Load ip_tables kernel module
      ansible.builtin.command:
        argv: [/sbin/modprobe, ip_tables]
      changed_when: false
      tags:
        - wgeasy

    - name: Enable ipv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
      tags:
        - wgeasy

    - name: Enable ipv4 src fwdmark
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.src_valid_mark
        value: "1"
        state: present
      tags:
        - wgeasy

    - name: Start pihole docker container
      community.docker.docker_container:
        name: pihole
        image: pihole/pihole
        env:
          WEBPASSWORD: "{{ pihole_password }}"
        ports:
          - "5353:80/tcp"
        volumes:
          - "{{ pihole_data_dir }}/pihole:/etc/pihole"
          - "{{ pihole_data_dir }}/dnsmasq.d:/etc/dnsmasq.d"
        restart_policy: "unless-stopped"
        networks:
          - name: wgeasy
            ipv4_address: "{{ wg_docker_network_addresses.pihole }}"
      tags:
        - pihole

    - name: Start wgeasy docker container
      community.docker.docker_container:
        name: wgeasy
        image: weejewel/wg-easy
        env:
          WG_HOST: "{{ wgeasy_host }}"
          PASSWORD: "{{ wgeasy_password }}"
          WG_DEFAULT_DNS: "{{ wg_docker_network_addresses.pihole }}"
        ports:
          - "51820:51820/udp"
          - "51821:51821/tcp"
        volumes:
          - "{{ wgeasy_data_dir }}:/etc/wireguard"
        restart_policy: "unless-stopped"
        capabilities:
          - "NET_ADMIN"
          - "SYS_MODULE"
        sysctls:
          "net.ipv4.conf.all.src_valid_mark": 1
          "net.ipv4.ip_forward": 1
        networks:
          - name: wgeasy
            ipv4_address: "{{ wg_docker_network_addresses.wgeasy }}"
      tags:
        - wgeasy
