---
- name: Wireguard Server
  hosts: all
  tags:
    - wireguard-server
    - wireguard
  vars:
    wgeasy_data_dir: "/opt/wgeasy"
    wgeasy_host: "{{ansible_host}}"
    wgeasy_password: "password"
  become: true
  roles:
    - role: wireguard
    - role: install_docker

  tasks:
    - name: Start and enable docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Start wgeasy docker container
      community.docker.docker_container:
        name: wgeasy
        image: weejewel/wg-easy
        env:
          WG_HOST: "{{ wgeasy_host }}"
          PASSWORD: "{{ wgeasy_password }}"
        ports:
          - "51820:51820/udp"
          - "51821:51821/tcp"
        volumes:
          - "{{ wgeasy_data_dir }}:/etc/wireguard"
        restart_policy: "unless-stopped"
        capabilities:
          - "NET_ADMIN"
          - "SYS_MODULE"
        sysctls:
          "net.ipv4.conf.all.src_valid_mark": 1
          "net.ipv4.ip_forward": 1
