- name: downloading docker gpg key
  ansible.builtin.get_url:
    url: "{{docker_repo_url}}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc

- name: fetching dpkg architecture
  shell: dpkg --print-architecture
  register: dpkg_arch

- name: add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{dpkg_arch.stdout}} signed-by=/etc/apt/trusted.gpg.d/docker.asc] {{docker_repo_url}} {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
