---
- name: install prerequisites for adding DNF repo
  ansible.builtin.dnf:
    name: dnf-utils
    state: present

- name: add Docker CE repo (DNF)
  ansible.builtin.shell: dnf config-manager --add-repo={{docker_repo_url}}

- name: install Docker CE (DNF)
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
