galaxy_info:
  author: Ian Shehadeh
  description: install and configure wireguard and wireguard devices

  license: MIT

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - all

    - name: Debian
      versions:
        - all

    - name: EL
      versions:
        - all

    - name: Fedora
      versions:
        - all

  galaxy_tags: []
