---
- name: Create Trilium directory
  ansible.builtin.file:
    path: "{{ trilium_dir }}"
    owner: "{{ trilium_user }}"
    group: "{{ trilium_group }}"
    state: directory

- name: Download and unarchive Trilium
  ansible.builtin.unarchive:
    src: "https://github.com/zadam/trilium/releases/download/v{{trilium_version}}/trilium-linux-{{trilium_arch}}-server-{{trilium_version}}.tar.xz"
    dest: "{{ trilium_dir }}"
    owner: "{{ trilium_user }}"
    group: "{{ trilium_group }}"
    remote_src: true

- name: Install Trilium systemd service
  ansible.builtin.template:
    src: trilium.service.j2
    dest: "{{ trilium_systemd_service_dir }}/radarr.service"
  notify: Restart Trilium
