---
# This file is intended to be included in a loop
# - `item.key` is the device name
# - `item.value` is the state, see wireguard_devices for details

- name: Remove wireguard device
  ansible.builtin.command:
    argv: ["/sbin/ip", "link", "del", "dev", "{{ item.key }}"]
  register: cmd_wg_device_del
  when: item.value.state == "absent" and item.key in ansible_interfaces
  changed_when: cmd_wg_device_del.rc == 0
  failed_when: cmd_wg_device_del.rc != 0
  tags:
    - wireguard_devices
